language: objective-c

osx_image: xcode7.1

before_install:
 - pip install cpp-coveralls

script:
 - ./gradlew clean assemble test --stacktrace

after_script:
 - ./gradlew simulatorKill

after_success:
 - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

